-- MySQL Script generated by MySQL Workbench
-- Wed Sep 21 10:58:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema books
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema books
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `books` DEFAULT CHARACTER SET utf8 ;
USE `books` ;

-- -----------------------------------------------------
-- Table `books`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `books`.`user` ;

CREATE TABLE IF NOT EXISTS `books`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `open_id` VARCHAR(45) NOT NULL COMMENT '微信openId',
  `real_name` VARCHAR(45) NOT NULL COMMENT '姓名或昵称',
  `icon` VARCHAR(255) NOT NULL,
  `dept_id` INT UNSIGNED NOT NULL COMMENT '所属部门id',
  `del_flag` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `books`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `books`.`role` ;

CREATE TABLE IF NOT EXISTS `books`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `cname` VARCHAR(45) NOT NULL COMMENT '角色中文名',
  `level` TINYINT UNSIGNED NOT NULL COMMENT '职位级别，0~10',
  `del_flag` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `books`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `books`.`user_role` ;

CREATE TABLE IF NOT EXISTS `books`.`user_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  `del_flag` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `books`.`permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `books`.`permission` ;

CREATE TABLE IF NOT EXISTS `books`.`permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `del_flag` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `books`.`role_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `books`.`role_permission` ;

CREATE TABLE IF NOT EXISTS `books`.`role_permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  `perm_id` INT NOT NULL,
  `del_flag` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `books`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `books`.`book` ;

CREATE TABLE IF NOT EXISTS `books`.`book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `user_id` INT NOT NULL,
  `type` TINYINT NOT NULL DEFAULT 5 COMMENT '书籍类型 1艺术 2小说 3科幻 4历史 5其它',
  `extra` TEXT NOT NULL,
  `del_flag` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `books`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `books`.`department` ;

CREATE TABLE IF NOT EXISTS `books`.`department` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '部门名称',
  `pid` INT UNSIGNED NOT NULL COMMENT '父部门id',
  `del_flag` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '部门';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
